# cloudbuild.yaml
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/flask-app:$COMMIT_SHA', '.']

options:
  logging: NONE  # Disable logging entirely

build:
  service_account: '455482298606-compute@developer.gserviceaccount.com'
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/flask-app:$COMMIT_SHA']

  # Update the container image in the GCE instance
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'instances'
      - 'update-container'
      - 'patel-flask-instance'
      - '--zone=${_ZONE}'
      - '--container-image=gcr.io/$PROJECT_ID/flask-app:$COMMIT_SHA'

substitutions:
  _ZONE: 'us-central1-a'  # default value

images:
  - 'gcr.io/$PROJECT_ID/flask-app:$COMMIT_SHA'
